### ISSUE TITLE
Tips getting started?

### ISSUE THREAD

**Issue by ctaggart** [booyaa/hello-spidermonkey#1]
Thanks for the HelloWorld! Any tips on how you figured this out? I may use this as a starting point, I'd like to load 'typescript.js' and call a few functions like I was [trying to do with chakracore](https://github.com/darfink/chakracore-rs/issues/21#issuecomment-327452792). Tips getting started.

**Comment by booyaa** [comment]
I used this test to get started: https://github.com/servo/rust-mozjs/blob/master/tests/evaluate.rs
